spring:
  datasource:
    url: jdbc:h2:mem:testdb
  sql:
    init:
      mode: never
      schema-locations: schema.sql
#      data-locations: data.sql

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: create

    show-sql: true